dist: trusty
sudo: required

language: c
before_install:
  - sudo add-apt-repository ppa:cloud-green/trusty-backports -y
  - sudo apt-get update -q
  - sudo apt-get install etcd
addons:
  apt:
    packages:
      - etcd
      - rake
      - psmisc
      - bison
      - git
      - gperf
      - cgroup-lite
      - libpam0g-dev
      - autotools-dev
      - libcap-dev
      - libargtable2-dev
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=""
  # - MRUBY_VERSION=master
branches:
  only:
    - master
cache:
  directories:
    - mruby

script:
  - rake consistent
  - rake compile
  - sudo /usr/bin/rake test:bintest
