dist: trusty
sudo: required

language: c
addons:
  apt:
    packages:
      - rake
      - bison
      - git
      - gperf
      - cgroup-lite
      - libpam0g-dev
      - autotools-dev
      - libcap-dev
      - libargtable2-dev
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=""
  # - MRUBY_VERSION=master
branches:
  only:
    - master
cache:
  directories:
    - mruby

script:
  - rake consistent
  - sudo /usr/bin/rake test:bintest
