deb:
  dockerfile: packages/dockerfiles/Dockerfile.debian
  build: .
  volumes:
    - .:/out:rw

rpm:
  dockerfile: packages/dockerfiles/Dockerfile.centos
  build: .
  volumes:
    - .:/out:rw

rpm6:
  dockerfile: packages/dockerfiles/Dockerfile.centos6
  build: .
  volumes:
    - .:/out:rw
